### PR TITLE
Update parser.js

### PR DESCRIPTION
**Pull request by nitinbansal1989**

### CODE REVIEW

**Comment by mcollina** [comment]
Why?
Can you add a unit test?

**Comment by nitinbansal1989** [comment]
I ran a load test from MQTTBOX client and it was sending reserved type of messages.
I checked it with mosquitto server and it was working fine with "reserved" type packets. 
So i thought it might be helpful if the this packet type is supported otherwise throwing exception.

**Comment by mcollina** [comment]
Ok, can you add a unit test?

**Comment by nitinbansal1989** [comment]
i think it would be something like this. Please review. Sry but i don't know the exact header value.

testParseGenerate('reserved', {
  cmd: 'reserved',
  retain: false,
  qos: 0,
  dup: false,
  length: 0
}, new Buffer([
  224, 0 // Header
]))

**Comment by mcollina** [comment]
can you please add it as a commit? Thanks.

**Comment by nitinbansal1989** [comment]
Test case added. Can you publish the updated package.

**Comment by mcollina** [comment]
the test is not part of this PR.

**Comment by mcollina** [comment]
On second thought.. why is MQTTBOX sending "reserved" packets?
Currently it errors the parser: https://github.com/mqttjs/mqtt-packet/blob/master/parser.js#L130.

This is a semver-major change if we add it, and I am not 100% sure it's a good idea.

I do not see https://github.com/workswithweb/MQTTBox the reserved packet being used.

**Comment by nitinbansal1989** [comment]
I also don't know, but it is sending them during load testing.

**Comment by mcollina** [comment]
It seems some data is getting corrupted during load testing. What are you benchmarking?

**Comment by nitinbansal1989** [comment]
I running the load testing on mosca server.

**Comment by mcollina** [comment]
Which version?
I'm not familiar with MQTTBox, is it working over websocket?

**Comment by nitinbansal1989** [comment]
You can add chrome extension of MQTT Box and it features as a standalone mqtt client app.
I check and found the following "reserved" packet header in mqtt specs.
http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html#fixed-header
I think that it should be added if specified in specs.

**Comment by mcollina** [comment]
I do not think so. That packet is not supported and it should not be using.
If MQTTBox is sending it, it's their fault.
Receiving a reserved packet errors the parser, and I think that is the right behavior.

IMHO this happens because some bits become corrupted or broken within the stream.

**Comment by nitinbansal1989** [comment]
Ok. Can you suggest me some other client where i can do a load test or something.

**Comment by mcollina** [comment]
This should work correctly: https://github.com/mqttjs/MQTT.js/blob/master/benchmarks/bombing.js

**Comment by wuhkuh** [comment]
@mcollina is correct, if we follow the MQTT 3.1.1 [specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Table_2.1_-) reserved packets may not be handled.

**Comment by nitinbansal1989** [comment]
@mcollina Thanks

**Pull request closed without merging**
