### PR TITLE
Strict validate subscribe flags, qos <= 2, and all reason codes

### PR DESCRIPTION
**Pull request by jedwards1211**

### CODE REVIEW

**Comment by jedwards1211** [comment]
@mcollina given the weird inconsistency between MQTT 4 and 5 connack return codes, I think it's best not to validate connack return codes at all...that was the only remaining thing so this should be good to merge

**Comment by jedwards1211** [comment]
Okay this should be good to go

**Comment by jedwards1211** [comment]
@mcollina okay i fixed the formatting.  Btw should there be a `yarn.lock` or `package-lock.json` in the repo?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
No, they are too much trouble for what they bring.

**Comment by jedwards1211** [comment]
I haven't encountered that viewpoint...You've never had that situation where a CI build suddenly fails because a newer version of a dependency gets installed?

**Comment by mcollina** [comment]
> I haven't encountered that viewpoint...You've never had that situation where a CI build suddenly fails because a newer version of a dependency gets installed?

Yes I did. It's very rare as I tend to avoid those dependencies.

**Pull request merged**
