### PR TITLE
Do not shift the pubcomp fixed header by qos

### PR DESCRIPTION
**Pull request by xadh00m**
This improves mqtt 3.1.1 protocol compatibility and prevents HiveMQ 3 broker
from disconnecting the client after subscription.

### CODE REVIEW

**Comment by mcollina** [comment]
Good catch!! Can you please add a unit test for it?
Il giorno mer 14 ott 2015 alle 16:47 Mirko Geissler <
notifications@github.com> ha scritto:

**Comment by xadh00m** [comment]
I´ve updated the test. Sorry for missing them.

**Comment by xadh00m** [comment]
Do you plan to update mqttjs with this fix soon? We are on hold updating to HiveMQ 3 at the moment because of it.

**Comment by mcollina** [comment]
Yes, it will be picked up automatically by MQTT.js, release coming soon

**Comment by mcollina** [comment]
Done as v3.4.4, reinstalling MQTT.js will pick up the new version.

**Comment by xadh00m** [comment]
Great work! Thank you.

**Pull request merged**
