### PR TITLE
fix build in mqttjs

### PR DESCRIPTION
**Pull request by scarry1992**
replace arrow function with usual declaration.

### CODE REVIEW

**Comment by scarry1992** [comment]
@mcollina, can you release that fix asap, that`s cracks install of mqtt.js

**Comment by mcollina** [comment]
Which fix?

**Comment by scarry1992** [comment]
@mcollina, mqttjs failed building with that version of mqtt-packet, I mistaken with arrow function

**Comment by scarry1992** [comment]
Parse error at 0:9030,65
npm ERR! prepareGitDep             result += currentValue.reduce((currentLength, value) => {
npm ERR! prepareGitDep                                                                  ^
npm ERR! prepareGitDep ERROR: Invalid assignment
npm ERR! prepareGitDep     at JS_Parse_Error.get (eval at <anonymous> (/home/sebu/.npm/_cacache/tmp/git-clone-ea9541ac/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
npm ERR! prepareGitDep     at fatal (/home/sebu/.npm/_cacache/tmp/git-clone-ea9541ac/node_modules/uglify-js/bin/uglifyjs:296:53)
npm ERR! prepareGitDep     at run (/home/sebu/.npm/_cacache/tmp/git-clone-ea9541ac/node_modules/uglify-js/bin/uglifyjs:240:9)
npm ERR! prepareGitDep     at ReadStream.<anonymous> (/home/sebu/.npm/_cacache/tmp/git-clone-ea9541ac/node_modules/uglify-js/bin/uglifyjs:173:9)
npm ERR! prepareGitDep     at ReadStream.emit (events.js:202:15)
npm ERR! prepareGitDep     at endReadableNT (_stream_readable.js:1129:12)
npm ERR! prepareGitDep     at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by scarry1992** [comment]
@mcollina, need release in npm with fix version 6.1.1

**Pull request merged**
