### PR TITLE
mqtt-packet side of fix for MQTTjs issue 235

### PR DESCRIPTION
**Pull request by mdickens**
Hi , 

Here are some proposed changes to add the session present bit support. Thank you in advance for checking it out and letting me know what you think.

- me

### CODE REVIEW

**Comment by mcollina** [comment]
This is perfect! Would you like to help maintaining this module? I think there might be some more issues like this one!

**Comment by mcollina** [comment]
I updated it to use booleans vs integers.

**Comment by mdickens** [comment]
Hi,

Sure, I would be happy to help maintaining this module any way that I can.
I'm glad you liked the fix.

Thanks!

**Comment by mcollina** [comment]
Added you to the mqtt-packet team! :). Please feel free to review all the parsing and send PRs according to CONTRIBUTING.md :).

**Pull request merged**
