### PR TITLE
Remove `noAssert` from buffer calls.

### PR DESCRIPTION
**Pull request by BridgeAR**
Refs https://github.com/nodejs/node/pull/18395

Ping @mcollina

### CODE REVIEW

**Comment by mcollina** [comment]
This guarantees increased performance in Node 4, 6, and 8. Why removing it now?

**Comment by BridgeAR** [comment]
That is your call. I personally do not believe that this is going to have any measurable performance difference when being used.

I went ahead and checked for all such entries to find modules that break because of the change. That was the case a couple of times (but not here).

Feel free to close this, if you think it should stay in there.

**Comment by mcollina** [comment]
It did when I put this in during the crankshaft era. I’ll check the benchmarks.

**Comment by mcollina** [comment]
performance is identical.

**Pull request merged**
