### PR TITLE
[Maintenance] Dependency updates, node 7 testing

### PR DESCRIPTION
**Pull request by wuhkuh**
- Updated dependencies
- Added node 7 tests

- Fix contributor links
- Updated docs, fixed typos
- Updated license year to 2017

### CODE REVIEW

**Comment by wuhkuh** [comment]
If this lands, consider incrementing the version to v5.2.2.

**Comment by mcollina** [comment]
what's your npm handle? I'll add you in.

**Comment by wuhkuh** [comment]
My NPM handle is @wuhkuh.
Contact details:

Wouter Klijn
contact@wuhkuh.com

**Comment by mcollina** [comment]
I've added you, feel free to release :D.

**Comment by mcollina** [comment]
@wuhkuh you should add a Release on github.

**Comment by wuhkuh** [comment]
@mcollina I'm on it!

**Comment by wuhkuh** [comment]
While I'm able to replicate a tarball and compressed (zip) file, it seems to differ quite a lot from your workflow. Are you using any sort of integration that I still have to set up?

**Comment by mcollina** [comment]
It seems all good. It's all creates by github automaically.

**Pull request merged**
